# Generated by Django 3.0.5 on 2020-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Фамилия', 'Имя', 'Отчество']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_class',
            new_name='Группа',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_admission',
            new_name='Дата_поступления',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='Дата_рождения',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='others',
            new_name='Другое',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='other_name',
            new_name='Отчество',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='passport',
            new_name='Паспорт',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='Регистрационный_номер',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_mobile_number',
            new_name='Телефон',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='Фамилия',
        ),
        migrations.RenameField(
            model_name='studentbulkupload',
            old_name='csv_file',
            new_name='csv_фаил',
        ),
        migrations.RenameField(
            model_name='studentbulkupload',
            old_name='date_uploaded',
            new_name='Дата_загрузки',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='Пол',
            field=models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('активен', 'Активен'), ('неактивен', 'Неактивен')], default='активен', max_length=10),
        ),
    ]
