# Generated by Django 3.0.5 on 2020-06-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200609_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_status',
            new_name='статус',
        ),
    ]
