# Generated by Django 3.0.5 on 2020-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['Студент', 'Семестр']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='class_for',
            new_name='Группа',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='balance_from_previous_term',
            new_name='Остаток_семестра',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='term',
            new_name='Семестр',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='session',
            new_name='Сессия',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='student',
            new_name='Студент',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='amount',
            new_name='Сумма',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice',
            new_name='Счёт',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='amount_paid',
            new_name='Выплаченная_сумма',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='date_paid',
            new_name='Дата_платежа',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='comment',
            new_name='Коментарий',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='invoice',
            new_name='Счёт',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Статус',
            field=models.CharField(choices=[('активный', 'Активный'), ('закрытый', 'Закрытый')], default='active', max_length=20),
        ),
    ]
