# Generated by Django 3.0.5 on 2020-06-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200610_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='invoice',
            new_name='Счёт',
        ),
    ]
