# Generated by Django 3.0.5 on 2020-06-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200610_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice',
            new_name='Счёт',
        ),
    ]
