# Generated by Django 3.0.5 on 2020-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20200610_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Счёт',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Счёт',
            new_name='invoice',
        ),
    ]
