# Generated by Django 3.0.5 on 2020-06-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20200610_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['Студент', 'Семестр']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='class_for',
            new_name='Группа',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='term',
            new_name='Семестр',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='session',
            new_name='Сессия',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='student',
            new_name='Студент',
        ),
    ]
