# Generated by Django 3.0.5 on 2020-06-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200610_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='amount_paid',
            new_name='Выплаченная_сумма',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='date_paid',
            new_name='Дата_платежа',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='comment',
            new_name='Коментарий',
        ),
    ]
