# Generated by Django 3.0.5 on 2020-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20200609_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Пол',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], default='мужской', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Статус',
            field=models.CharField(choices=[('активный', 'Активный'), ('неактивный', 'Неактивный')], default='активный', max_length=10),
        ),
    ]
